# mkdocs.yml
site_name: wandb-addons

theme:
  name: material
  logo: ./assets/wandb-dots-logo.svg
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link

plugins:
  - mkdocstrings
  - search
  - minify
  - glightbox
  - mkdocs-jupyter:
      include_source: True


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - 'Dataset': 'dataset/dataset_loading.md'
  - 'Report': 'report.md'
  - 'Integrations':
    - 'Ciclo': 'ciclo/ciclo.md'
    - '🧨 Diffusers':
      - 'Overview': 'diffusers/overview'
      - 'Stable Diffusion': 'diffusers/stable_diffusion.md'
      - 'Kandinsky': 'diffusers/kandinsky.md'
      - 'Auto Integrate': 'diffusers/auto_integrate.md'
      - 'Base Callbacks': 'diffusers/base.md'
    - '🦄 Keras':
      - 'Callbacks': 'keras/keras.md'
      - 'KerasCV':
        - 'Object-Detection': 'keras/object_detection.md'
    - 'MonAI': 'monai/monai.md'
    - 'Ultralytics': 'ultralytics/yolo.md'
  - 'Prompts': 'prompts/tracer.md'
  - 'Utils': 'utils.md'

repo_url: https://github.com/soumik12345/wandb-addons